frameworks:
  laravel:
    known_sinks:
      - to
      - route
      - action
      - redirect
      - render
      - generate
      - fullUrl
      - getSchemeAndHttpHost
  symfony:
    known_sinks:
      - generate
      - render
      - redirect
      - url
      - path
